app:
  name: "web_app"
  mode: "dev"
  port: 8081
  jwt_secret: "kkkk"
log:
  level: "debug"
  filename: "./web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  user: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  dbname: "gotest"
redis:
  host: "127.0.0.1"
  port: 6379
  password: "dypn"
  db: 0
  pool_size: 100